version: "3.3"

services:
  jenkins_prod:
    build:
      context: .
      args:
        GITHUB_OAUTH_CLIENT_ID: a1e0370dd057128933eb
        GITHUB_REPO_OWNER: RIOT-OS
        GITHUB_CI_USERNAME: riot-hil-bot
        CASC_ENV: prod
        JENKINS_PREFIX: jenkins
        JENKINS_URL: https://hil.riot-os.org/jenkins/
    image: riot-hil-jenkins-ci/prod:latest

    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/riot-hil:/run/secrets
      - /opt/riot-hil-jenkins-home:/var/jenkins_home
    ports:
      - "8080:8080"
