version: "3.3"

services:
  jenkins:
    build:
      context: .
      args:
        GITHUB_OAUTH_CLIENT_ID: e094c0b91f5b47c8b6f0
        GITHUB_REPO_OWNER: riot-hil-bot
        GITHUB_CI_USERNAME: riot-hil-bot
        JENKINS_PREFIX: staging-hil
        CASC_ENV: live
    image: riot-hil-jenkins-ci/staging:latest

    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/riot-staging-hil:/run/secrets
    ports:
      - "8081:8080"