version: "3.3"

# For testing this should be run without persistent storage
# Only uncomment if testing things that require this
#volumes:
#  local_jenkins_home:

services:
  jenkins:
    build:
      context: .
      args:
        GITHUB_OAUTH_CLIENT_ID: 83666a7803532cb37ecd
        GITHUB_REPO_OWNER: riot-hil-bot
        GITHUB_CI_USERNAME: riot-hil-bot
        JENKINS_PREFIX:
        CASC_ENV: staging
        JENKINS_URL: https://localhost:8080
    image: riot-hil-jenkins-ci/local:latest

    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/local:/run/secrets
      #- local_jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
