version: "3.3"

volumes:
  staging_jenkins_home:

services:
  jenkins_staging:
    build:
      context: .
      args:
        CASC_ENV: staging
    environment:
      GITHUB_UID: 4d72882f474d4cb49e4961851110a935
      JENKINS_OPTS: "--prefix=/jenkins-staging"
      JENKINS_URL: https://hil.riot-os.org/jenkins-staging/
      LIB_VERSION: main
    image: riot-hil-jenkins-ci/staging:latest

    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/staging:/run/secrets
      - staging_jenkins_home:/var/jenkins_home
    ports:
      - "8081:8080"
