version: "3.3"

services:
  jenkins:
    build:
      context: .
      args:
        GITHUB_OAUTH_CLIENT_ID: ${GITHUB_OAUTH_CLIENT_ID}
        GITHUB_REPO_OWNER: ${GITHUB_REPO_OWNER}
        GITHUB_CI_USERNAME: ${GITHUB_CI_USERNAME}
        JENKINS_PREFIX: ${JENKINS_PREFIX}
    image: riot-hil-jenkins-ci/${IMAGE_NAME}:${IMAGE_TAG}
    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/riot-staging-hil:/run/secrets
    ports:
      - "8081:8080"
