version: "3.3"

services:
  jenkins_prod:
    build:
      context: .
      args:
        CASC_ENV: prod
    environment:
      GITHUB_UID: 76e4c9b29b8c42479de5ea697572226c
      JENKINS_OPTS: "--prefix=/jenkins"
      JENKINS_URL: https://hil.riot-os.org/jenkins/
      LIB_VERSION: main
    image: riot-hil-jenkins-ci/prod:latest

    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/prod:/run/secrets
      - /opt/riot-hil-jenkins-home:/var/jenkins_home
    ports:
      - "8080:8080"
