version: "3.3"

volumes:
  prod_jenkins_home:

services:
  jenkins:
    build:
      context: .
      args:
        GITHUB_OAUTH_CLIENT_ID: 9c40627c9ba07be2578a
        GITHUB_REPO_OWNER: RIOT-OS
        GITHUB_CI_USERNAME: riot-ci
        CASC_ENV: prod
        JENKINS_PREFIX: hil
        JENKINS_URL: https://ci.riot-os.org/hil/
    image: riot-hil-jenkins-ci/prod:latest

    volumes:
      - /opt/riot-hil-jenkins-ci-secrets/riot-hil:/run/secrets
      - prod_jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
