version: "3.3"

volumes:
  jenkins_home:

services:
  jenkins:
    build:
      context: .
      args:
        CASC_ENV: local
    environment:
      GITHUB_UID: 0605d80e1d5c45b7b71a2a82d09f3caa
      JENKINS_OPTS: "--prefix="
      JENKINS_URL: https://localhost:8080
      LIB_VERSION: main
    image: riot-hil-jenkins-ci/local:latest
    volumes:
      - ~/.ssh:/run/secrets
      - jenkins_home:/var/jenkins_home
    network_mode: "host"
