jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${ADMIN_0}"
        - "Overall/Administer:${ADMIN_1}"
        - "Overall/Administer:${ADMIN_2}"
        - "Overall/Read:authenticated"
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "Job/Read:authenticated"
        - "View/Read:anonymous"
        - "View/Read:authenticated"