jenkins:
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "${readFile:${SECRETS}/oauth_client_id}"
      clientSecret: "${readFile:${SECRETS}/oauth_secrets}"
      oauthScopes: "read:org,user:email"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:MrKevinWeiss"
        - "Overall/Administer:ozfox"
        - "Overall/Administer:cgundogan"
        - "Overall/Administer:MarcelStenzel"
        - "Overall/Read:authenticated"
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "Job/Read:authenticated"
        - "View/Read:anonymous"
        - "View/Read:authenticated"