jenkins:
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "${readFile:${SECRETS}/oauth_client_id}"
      clientSecret: "${readFile:${SECRETS}/oauth_secrets}"
      oauthScopes: "read:org,user:email"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:MrKevinWeiss"
        - "Overall/Administer:ozfox"
        - "Overall/Administer:cgundogan"
        - "Overall/Administer:MichelRottleuthner"
        - "Overall/Administer:MarcelStenzel"
        - "Overall/Read:authenticated"
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "Job/Read:authenticated"
        - "View/Read:anonymous"
        - "View/Read:authenticated"
        - "Job/Build:bergzand"
        - "Job/Cancel:bergzand"
        - "Job/Read:bergzand"
        - "Run/Replay:bergzand"
        - "Run/Update:bergzand"
        - "View/Read:bergzand"
        - "Agent/Build:bergzand"
        - "Job/Build:pokgak"
        - "Job/Cancel:pokgak"
        - "Job/Read:pokgak"
        - "Run/Replay:pokgak"
        - "Run/Update:pokgak"
        - "View/Read:pokgak"
        - "Agent/Build:pokgak"
        - "Job/Build:kaspar030"
        - "Job/Cancel:kaspar030"
        - "Job/Read:kaspar030"
        - "Run/Replay:kaspar030"
        - "Run/Update:kaspar030"
        - "View/Read:kaspar030"
        - "Agent/Build:kaspar030"
        - "Job/Build:dylad"
        - "Job/Cancel:dylad"
        - "Job/Read:dylad"
        - "Run/Replay:dylad"
        - "Run/Update:dylad"
        - "View/Read:dylad"
        - "Agent/Build:dylad"
        - "Job/Build:miri64"
        - "Job/Cancel:miri64"
        - "Job/Read:miri64"
        - "Run/Replay:miri64"
        - "Run/Update:miri64"
        - "View/Read:miri64"
        - "Agent/Build:miri64"
        - "Job/Build:leandrolanzieri"
        - "Job/Cancel:leandrolanzieri"
        - "Job/Read:leandrolanzieri"
        - "Run/Replay:leandrolanzieri"
        - "Run/Update:leandrolanzieri"
        - "View/Read:leandrolanzieri"
        - "Agent/Build:leandrolanzieri"
        - "Job/Build:ngandrass"
        - "Job/Cancel:ngandrass"
        - "Job/Read:ngandrass"
        - "Run/Replay:ngandrass"
        - "Run/Update:ngandrass"
        - "View/Read:ngandrass"
        - "Agent/Build:ngandrass"
